config/routes.rb
Winnipegrb::Application.routes.draw do
  devise_for :users

  get "ideas/new" => "ideas#new", :as => "new_idea"
  post "ideas/create" => "ideas#create", :as => "ideas"
  root :to => "ideas#index"

  resources :ideas, except: [:edit, :show] do
    put 'upvote', on: :member
  end

  resources :projects, only: [:new, :create]

end

app/models/idea.rb
class Idea < ActiveRecord::Base
  attr_accessible :description, :title, :project_id

  validates_presence_of :description, :title

  belongs_to :project
  has_many :votes

  def upvote!(user)
    vote = self.votes.build(user_id: user.id)
    vote.save!
  end

  def project_name
    project ? project.name : ""
  end

  def total_votes
    self.votes.count
  end

end

app/models/project.rb
class Project < ActiveRecord::Base
  attr_accessible :name

  has_many :ideas

  validates_presence_of :name
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me
  # attr_accessible :title, :body

  has_many :votes
end

app/models/vote.rb
class Vote < ActiveRecord::Base
  attr_accessible :user_id, :idea_id
  validates_presence_of   :user_id, :idea_id
  validates_uniqueness_of :user_id, scope: :idea_id

  belongs_to :idea
  belongs_to :user
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
  before_filter :authenticate_user!
end

app/controllers/ideas_controller.rb
class IdeasController < ApplicationController
  skip_before_filter :authenticate_user!, only: :index
  respond_to :html, except: [:update, :upvote]
  respond_to :json, only: [:update, :upvote]
  
  def index
    @ideas = Idea.all
  end

  def new
    @idea = Idea.new
  end

  def create
    @idea = Idea.new(params["idea"])
    if @idea.save
      redirect_to :root
    else
      render "new"
    end
  end

  def upvote
    @idea = Idea.find(params[:id])
    @idea.upvote! current_user
    render json: {total_votes: @idea.total_votes}
  rescue
    render json: {error: "You have already voted on this idea!"}
  end
  
  def update
  	@idea = Idea.find(params[:id])
  	@idea.update_attributes(params[:idea])
    respond_with @idea
  end
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController

    def new
        @project = Project.new
    end

    def create
        @project = Project.new(params["project"])
        if @project.save
            redirect_to :root, notice: "Project successfully created"
        else
            render "new"
        end
    end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/ideas/_idea.html.slim
li.idea data-bind="attr: {id: 'idea-' + id(), 'data-target': id}"
  .row
    .idea-error &nbsp;

    .col-md-2
      .total-votes  data-bind="text: total_votes" 
      .upvote data-bind="click: upvote" == image_tag "golden_boy.png"
      
    .idea-content.col-md-10
        h3.title data-bind="text: title"
        .description.lead data-bind="text: description"
        .project data-bind='text: projectName'
        -if user_signed_in?
          button.edit data-bind='click: edit' Edit 
        
    .idea-form.col-md-10
      = form_for(Idea.new, remote: true) do |f|
        .form-group = f.text_field :title, class: 'form-control', 'data-bind' => 'value: newTitle'
        .form-group = f.text_field :description, class: 'form-control', 'data-bind' => 'value: newDescription'
        = f.submit 'Save', class: 'save', 'data-bind' => 'click: save'
        = f.button 'Cancel', class: 'cancel', 'data-bind' => 'click: cancel'

app/views/ideas/index.html.slim
#ideas
  h1 Ideas
  = link_to "Add New Idea", new_idea_path

  ul data-bind="foreach: ideas"
    = render partial: 'idea'

  .no-ideas-yet.alert.alert-info data-bind='visible: empty'
    | No ideas yet. 
    = link_to "Add one", new_idea_path
    | ?

- content_for :javascripts
  javascript:
    window.ideas = #{raw @ideas.to_json(include: :project, methods: :total_votes)}
    
  coffee:
    ko.applyBindings new WinniVote.IdeasViewModel(ideas)

app/views/ideas/new.html.slim
#new-idea-submission
  h1 New idea
  = simple_form_for @idea do |f|
    = f.input :title
    = f.input :description
    = f.input :project_id, collection: Project.all
    = f.button :submit, 'Create Idea'
    = link_to "Cancel", :back, class: 'cancel'

app/views/layouts/_user_navbar.html.slim
nav#user_nav.user.navbar.navbar-inverse.navbar-fixed-top role='navigation'
  .container
    .navbar-header
      button.navbar-toggle type="button" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1"
        span.sr-only Toggle navigation
        span.icon-bar
        span.icon-bar
        span.icon-bar
      a.navbar-brand href=root_path Winnivote
      
    #bs-example-navbar-collapse-1.collapse.navbar-collapse
      ul.nav.navbar-nav
        li= link_to "Create project", new_project_path
        - unless current_user.blank?
          li= link_to "Sign out", destroy_user_session_path, method: :delete
        - else
          li= link_to "Sign in", new_user_session_path
          li= link_to "Sign up", new_user_registration_path

app/views/layouts/application.html.slim
doctype html
html
  head
    title WinniVote
    = stylesheet_link_tag    "application", media: "all", debug: true
    = csrf_meta_tags

  body
    = render :partial => "layouts/user_navbar"
    .container
      #notification_area
        - flash.each do |key, value|
          .notification class='#{key}' 
            button.close type='button' class='close' data-dismiss='alert' x
            = value

      = yield

    = javascript_include_tag "application" 
    
    == yield :javascripts

app/views/projects/new.html.slim
#new-project-submission
  h1 New project
  = simple_form_for @project do |f|
    = f.input :name
    = f.button :submit, 'Create Project'
    = link_to "Cancel", :back, class: 'cancel'